name: Build

on:
  push:
    branches:
      - master  # Adjust the branch as needed

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  job:
    name: Build + Unittests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile Min-Max/TicTacToeBoard DLL
        run: |
          g++ -std=c++17 -static -shared -o ./classic_games/tictactoe/agent/min_max.dll ./classic_games/tictactoe/agent/min_max.cpp ./classic_games/tictactoe/model/board.cpp ./classic_games/util/converter.cpp
          g++ -std=c++17 -static -shared -o ./classic_games/tictactoe/model/board.dll ./classic_games/tictactoe/model/board.cpp ./classic_games/util/converter.cpp
      - name: Change File permission DLL
        run: |
          Set-ItemProperty -Path "./classic_games/tictactoe/agent/min_max.dll" -Name "Attributes" -Value ((Get-ItemProperty -Path "./classic_games/tictactoe/agent/min_max.dll").Attributes -bOr [System.IO.FileAttributes]::ReadOnly)
          Set-ItemProperty -Path "./classic_games/tictactoe/model/board.dll" -Name "Attributes" -Value ((Get-ItemProperty -Path "./classic_games/tictactoe/model/board.dll").Attributes -bOr [System.IO.FileAttributes]::ReadOnly)

      - name: List Workspace Contents
        run: |
          cd ./classic_games/tictactoe/model
          dir
      - name: List Workspace Contents
        run: |
          cd ./classic_games/tictactoe/agent
          dir
      - name: Test
        run: |
          cd D:\a\classic-games\classic-games\classic_games\tictactoe\agent
          objdump -p min_max.dll
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Unittest on tictactoe
        run: |
          python -m unittest discover -s tests/tictactoe -p "test_*.py"
      - name: Unittest on connectfour
        run: |
          python -m unittest discover -s tests/connectfour -p "test_*.py"
      - name: Unittest on sudoku
        run: |
          python -m unittest discover -s tests/sudoku -p "test_*.py"
      - name: Unittest on snake
        run: |
          python -m unittest discover -s tests/snake -p "test_*.py"
      - name: Unittest on chess
        run: |
          python -m unittest discover -s tests/chess -p "test_*.py"