name: Build & Test TicTacToe

on:
  push:
    paths: ["classic_games/tictactoe/**", "classic_games/util/**", "tests/tictactoe/**"]

jobs:
  job:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        c-plus-version: ["c++17"]

    name: Build & Test TicTacToe on Python ${{ matrix.python-version }} and ${{ matrix.c-plus-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Compile DLL files with ${{ matrix.c-plus-version }}
        run: |
          g++ -std=${{ matrix.c-plus-version }} -static -shared -o ./classic_games/tictactoe/agent/min_max.dll ./classic_games/tictactoe/agent/min_max.cpp ./classic_games/tictactoe/model/board.cpp ./classic_games/util/converter.cpp
          g++ -std=${{ matrix.c-plus-version }} -static -shared -o ./classic_games/tictactoe/model/board.dll ./classic_games/tictactoe/model/board.cpp ./classic_games/util/converter.cpp
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Run Unittests
        run: |
          python -m unittest discover -s tests/tictactoe -p "test_*.py"