name: Unittest

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Unittest on tictactoe
        run: |
          python -m unittest discover -s tests/tictactoe -p "test_*.py"
      - name: Unittest on fourwins
        run: |
          python -m unittest discover -s tests/fourwins -p "test_*.py"
      - name: Unittest on sudoku
        run: |
          python -m unittest discover -s tests/sudoku -p "test_*.py"